name: dotnet publish

on:
  release:
    types: [ "published" ]
    
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  publish:
    runs-on: windows-latest
    strategy:
      matrix:
        runtime: ['win-x86', 'win-x64', 'win-arm64']
    steps:
    - uses: actions/checkout@v4
    - name: Run the Cake script
      uses: cake-build/cake-action@v3
      with:
        script-path: build.cake
        target: Setup
        arguments: |
          app-version: ${{ github.event.release.tag_name }}
          app-runtime: ${{ matrix.runtime }}
    - name: Upload the artifacts
      uses: AButler/upload-release-assets@v3.0
      with: 
        files: '.artifacts/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.event.release.tag_name }}
